#!/bin/sh

"C:\Program Files\Git\bin\bash.exe" $0/../pre-commit.sh
# "C:\Program Files\Git\git-bash.exe" $0/../pre-commit.sh

status=$?
exit $status


# list all build ins 
# compgen -b

# get all available commands
#compgen -c

# powershell $0/../pre-commit.ps1 &

