#!/bin/sh

exec "C:\Program Files\Git\git-bash.exe" $0/../pre-commit.sh
exec "C:\Program Files\Git\git-bash.exe" $0/../pre-commit.sh

# list all build ins 
# compgen -b

# get all available commands
#compgen -c

# powershell $0/../pre-commit.ps1 &

exit 1